import type { Metadata } from "next";
import NavBar from "./components/Navbar";
import { ReactNode } from "react";
import "./styles/globals.css";

interface LayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Gym Tracker App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps) => (
  <html lang="en">
    <body>
      <NavBar />
      <main>{children}</main>
    </body>
  </html>
);

export default RootLayout;
